[phases]
setup = "apt-get update && apt-get install -y libpq-dev libpng-dev libjpeg-dev libfreetype6-dev"
install = "composer install --no-interaction --prefer-dist --optimize-automation --no-dev"
build = "npm install && npm run build"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"

[phases.setup.nixLibraries]
libpng = "libpng-dev"
libjpeg = "libjpeg-dev"
freetype = "libfreetype6-dev"

[phases.install.nixLibraries]
php = { pkg = "php82", version = "8.2" }
composer = { pkg = "composer", version = "2.6.4" }

[phases.build.nixLibraries]
nodejs = { pkg = "nodejs", version = "18.x" }
