[build]
  builder = "nixpacks"
  buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm ci && npm run build"
  installCommand = "php artisan key:generate --force"
  startCommand = "php -S 0.0.0.0:${PORT} public/index.php"

[deploy]
  startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"

[environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.6"
