[build]
  builder = "nixpacks"
  buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm ci && npm run build"
  installCommand = "php artisan key:generate --force"
  startCommand = "./start-server"

[deploy]
  startCommand = "php artisan migrate --force && ./start-server"

[environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.6"
