[build]
  builder = "nixpacks.toml"
  buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev"
  installCommand = "php artisan key:generate --force"
  startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT}"

[deploy]
  startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"

[environment]
  NODE_VERSION = "18.x"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.6.4"
